galaxy_info:
  author: Taras Kozlovskyi
  company: QuintaGroup
  license: Apache
  min_ansible_version: 2.2
  platforms:
   - name: Fedora
     versions:
      - any
  categories:
   - system
dependencies: []