- hosts: "servers"
  gather_facts: false
  tasks:
    - name: 'install python2'
      raw: sudo dnf install python2 python-simplejson python-dnf libselinux-python -y -q
    - name: 'install nodejs'
      raw: sudo dnf install nodejs -y -q
    - name: 'install bower'
      raw: sudo npm install bower -g
    - name: 'install gulp'
      raw: sudo npm install gulp -g
  tags:
   - servers_pre

- hosts: "servers"
  roles:
   - role: ansible-role-common
     become: yes
   - role: ansible-role-buildout-auction
  tags:
   - build